# Uncomment this line to define a global platform for your project
#platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'


target 'Pedometer' do

  use_frameworks!

  pod 'GoogleMaps'
end